import { Vehicle } from "./types";

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: "veh-1",
    slug: "honda-hr-v-exl-2021",
    name: "Honda HR-V EXL",
    brand: "Honda",
    model: "HR-V",
    version: "1.8 Flex EXL 16V Aut.",
    manufacturingYear: 2021,
    modelYear: 2021,
    category: "suv",
    engine: "1.8",
    fuel: "flex",
    transmission: "automatico",
    powerHp: 140,
    mileage: 68500,
    price: 104900,
    entryValue: 20000,
    installmentsCount: 48,
    installmentValue: 1899,
    acceptsTrade: true,
    acceptsFinancing: true,
    color: "Prata Platinum",
    doors: 4,
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      "Airbags frontais e laterais",
      "Central multimídia com Apple CarPlay e Android Auto",
      "Câmera de ré multivisão",
      "Sensor de estacionamento",
      "Bancos de couro",
      "Faróis de neblina",
      "Rodas de liga leve aro 17",
      "Piloto automático",
      "Controle de tração e estabilidade",
      "Freio de estacionamento eletrônico com Brake Hold"
    ],
    singleOwner: true,
    dealerMaintained: true,
    description: "Honda HR-V EXL 2021 em estado impecável de conservação. Veículo de único dono, com todas as revisões feitas na concessionária autorizada e laudo cautelar 100% aprovado. Excelente espaço interno com sistema Magic Seat, conforto superior e alta confiabilidade mecânica.",
    images: [
      "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1550345332-09a3af9c702f?auto=format&fit=crop&q=80&w=1200"
    ],
    mainImageIndex: 0,
    status: "disponivel",
    isFeatured: true,
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-20T14:30:00.000Z",
  },
  {
    id: "veh-2",
    slug: "toyota-corolla-xei-2020",
    name: "Toyota Corolla XEi",
    brand: "Toyota",
    model: "Corolla",
    version: "2.0 Dynamic Force Flex Aut.",
    manufacturingYear: 2020,
    modelYear: 2020,
    category: "sedan",
    engine: "2.0",
    fuel: "flex",
    transmission: "cvt",
    powerHp: 177,
    mileage: 72300,
    price: 112900,
    entryValue: 25000,
    installmentsCount: 48,
    installmentValue: 2049,
    acceptsTrade: true,
    acceptsFinancing: true,
    color: "Branco Pérola",
    doors: 4,
    features: [
      "Ar-condicionado automático",
      "Direção eletroassistida",
      "7 Airbags (frontais, laterais, cortina e joelho)",
      "Central multimídia Toyota Play 8 polegadas",
      "Câmera de ré com linhas guias",
      "Bancos em couro preto",
      "Faróis em LED com acendimento automático",
      "Rodas de liga leve aro 17 com acabamento diamantado",
      "Controle de estabilidade (VSC) e tração (TRC)",
      "Assistente de partida em rampa (HAC)",
      "Chave presencial Smart Entry com partida por botão Start/Stop"
    ],
    singleOwner: false,
    dealerMaintained: true,
    description: "Toyota Corolla XEi 2020 nova geração. Motor 2.0 Dynamic Force de 177cv e câmbio Direct Shift de 10 velocidades com a primeira marcha mecânica. Sedã de referência em durabilidade, segurança e valor de revenda.",
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200"
    ],
    mainImageIndex: 0,
    status: "disponivel",
    isFeatured: true,
    createdAt: "2026-08-05T11:00:00.000Z",
    updatedAt: "2026-08-21T16:00:00.000Z",
  },
  {
    id: "veh-3",
    slug: "jeep-compass-limited-2019",
    name: "Jeep Compass Limited",
    brand: "Jeep",
    model: "Compass",
    version: "2.0 Tigershark Flex Aut.",
    manufacturingYear: 2019,
    modelYear: 2019,
    category: "suv",
    engine: "2.0",
    fuel: "flex",
    transmission: "automatico",
    powerHp: 166,
    mileage: 81900,
    price: 119900,
    entryValue: 25000,
    installmentsCount: 48,
    installmentValue: 2169,
    acceptsTrade: true,
    acceptsFinancing: true,
    color: "Cinza Antique",
    doors: 4,
    features: [
      "Ar-condicionado dual zone",
      "Direção elétrica progressiva",
      "Airbags frontais, laterais e de cortina",
      "Central multimídia Uconnect 8.4 polegadas",
      "Painel de instrumentos digital configurável em TFT de 7 pol.",
      "Sensor de ponto cego",
      "Sensor de estacionamento dianteiro e traseiro com Park Assist",
      "Bancos em couro com ajuste elétrico para o motorista",
      "Faróis de xenônio com DRL em LED",
      "Rodas aro 19 diamantadas"
    ],
    singleOwner: false,
    dealerMaintained: false,
    description: "Jeep Compass versão topo de linha Limited Flex. SUV sofisticado, muito confortável e com acabamento refinado. Conta com Park Assist (estaciona sozinho), monitor de ponto cego e central multimídia completa.",
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&q=80&w=1200"
    ],
    mainImageIndex: 0,
    status: "disponivel",
    isFeatured: true,
    createdAt: "2026-08-08T09:30:00.000Z",
    updatedAt: "2026-08-22T10:15:00.000Z",
  },
  {
    id: "veh-4",
    slug: "vw-polo-highline-2022",
    name: "VW Polo Highline",
    brand: "Volkswagen",
    model: "Polo",
    version: "1.0 200 TSI Flex Aut.",
    manufacturingYear: 2022,
    modelYear: 2022,
    category: "hatch",
    engine: "1.0",
    fuel: "flex",
    transmission: "automatico",
    powerHp: 128,
    mileage: 36200,
    price: 88900,
    entryValue: 18000,
    installmentsCount: 48,
    installmentValue: 1169,
    acceptsTrade: true,
    acceptsFinancing: true,
    color: "Vermelho Sunset",
    doors: 4,
    features: [
      "Ar-condicionado digital Climatronic",
      "Direção elétrica",
      "Painel Digital Active Info Display 10.25 polegadas",
      "Central multimídia VW Play 10 polegadas",
      "Câmera de ré e sensores dianteiros/traseiros",
      "Bancos com revestimento em couro sintético Native",
      "Faróis com iluminação diurna em LED",
      "Rodas de liga leve aro 17",
      "Chave presencial Kessy com partida por botão",
      "Controle eletrônico de estabilidade (ESC)"
    ],
    singleOwner: true,
    dealerMaintained: true,
    description: "Volkswagen Polo Highline 200 TSI com baixíssima quilometragem (apenas 36.200 km). Motor turbo potente e muito econômico, equipado com o painel 100% digital Active Info Display e multimídia VW Play.",
    images: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200"
    ],
    mainImageIndex: 0,
    status: "disponivel",
    isFeatured: true,
    createdAt: "2026-08-10T14:20:00.000Z",
    updatedAt: "2026-08-23T11:00:00.000Z",
  },
  {
    id: "veh-5",
    slug: "yamaha-mt-03-abs-2023",
    name: "Yamaha MT-03 ABS",
    brand: "Yamaha",
    model: "MT-03",
    version: "321cc ABS",
    manufacturingYear: 2023,
    modelYear: 2023,
    category: "moto",
    engine: "321cc",
    fuel: "gasolina",
    transmission: "manual",
    powerHp: 42,
    mileage: 9800,
    price: 26900,
    entryValue: 5000,
    installmentsCount: 36,
    installmentValue: 499,
    acceptsTrade: true,
    acceptsFinancing: true,
    color: "Midnight Black",
    doors: 0,
    features: [
      "Freios ABS de dois canais",
      "Painel 100% digital multifuncional em LCD",
      "Farol com projetor em LED e luz de posição",
      "Lanternas e setas em LED",
      "Suspensão dianteira invertida (Upside Down)",
      "Shift Light configurável",
      "Computador de bordo completo"
    ],
    singleOwner: true,
    dealerMaintained: true,
    description: "Yamaha MT-03 ABS 2023 impecável com menos de 10.000 km rodados. Motor bicilíndrico de 42cv ágil e empolgante, suspensão invertida e design agressivo da família Master of Torque.",
    images: [
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=1200",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=1200"
    ],
    mainImageIndex: 0,
    status: "disponivel",
    isFeatured: true,
    createdAt: "2026-08-12T16:00:00.000Z",
    updatedAt: "2026-08-24T09:00:00.000Z",
  }
];
